version: '2'
services:
    blog-app:
        image: blog
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - 'SPRING_PROFILES_ACTIVE=prod,swagger'
            - 'EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka'
            - 'SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config'
            - 'SPRING_DATASOURCE_URL=jdbc:mysql://blog-mysql:3306/blog?useUnicode=true&characterEncoding=utf8&useSSL=false'
            - 'SECURITY_OAUTH2_CLIENT_ACCESS_TOKEN_URI=http://keycloak:9080/auth/realms/jhipster/protocol/openid-connect/token'
            - 'SECURITY_OAUTH2_CLIENT_USER_AUTHORIZATION_URI=http://keycloak:9080/auth/realms/jhipster/protocol/openid-connect/auth'
            - SECURITY_OAUTH2_CLIENT_CLIENT_ID=web_app
            - SECURITY_OAUTH2_CLIENT_CLIENT_SECRET=web_app
            - SECURITY_OAUTH2_CLIENT_SCOPE=openid profile email
            - 'SECURITY_OAUTH2_RESOURCE_USER_INFO_URI=http://keycloak:9080/auth/realms/jhipster/protocol/openid-connect/userinfo'
            - JHIPSTER_SLEEP=30
            - 'SPRING_DATA_JEST_URI=http://blog-elasticsearch:9200'
            - JHIPSTER_REGISTRY_PASSWORD=admin
        ports:
            - '8080:8080'
    blog-mysql:
        image: 'mysql:5.7.20'
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=blog
        command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
    blog-elasticsearch:
        image: 'elasticsearch:5.6.13'
        command: '-Enetwork.host=0.0.0.0 -Ediscovery.type=single-node'
        environment:
            - ES_JAVA_OPTS=-Xms1024m -Xmx1024m
    
    shop-app:
        image: shop
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - 'SPRING_PROFILES_ACTIVE=prod,swagger'
            - 'EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka'
            - 'SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config'
            - 'SPRING_DATASOURCE_URL=jdbc:mysql://shop-mysql:3306/shop?useUnicode=true&characterEncoding=utf8&useSSL=false'
            - SECURITY_OAUTH2_CLIENT_CLIENT_ID=internal
            - SECURITY_OAUTH2_CLIENT_CLIENT_SECRET=internal
            - 'SECURITY_OAUTH2_RESOURCE_USER_INFO_URI=http://keycloak:9080/auth/realms/jhipster/protocol/openid-connect/userinfo'
            - JHIPSTER_SLEEP=30
            - 'SPRING_DATA_JEST_URI=http://shop-elasticsearch:9200'
            - JHIPSTER_REGISTRY_PASSWORD=admin
    shop-mysql:
        image: 'mysql:5.7.20'
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=shop
        command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
    shop-elasticsearch:
        image: 'elasticsearch:5.6.13'
        command: '-Enetwork.host=0.0.0.0 -Ediscovery.type=single-node'
        environment:
            - ES_JAVA_OPTS=-Xms1024m -Xmx1024m
    
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
    keycloak:
        extends:
            file: keycloak.yml
            service: keycloak
